-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;


ENTITY top_tb IS
generic (
	k : integer := 8 -- 10 for Quartus, 8 for ModelSim 
);
END top_tb ;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--

ARCHITECTURE struct OF top_tb IS

   -- Architecture declarations

   -- Internal signal declarations

  
	
COMPONENT top IS
generic (
	k : integer := 8 -- 10 for Quartus, 8 for ModelSim 
);
port(
		----------INPUTS----------
		Clkin:   IN STD_LOGIC;
		PORT_SW: IN STD_LOGIC_VECTOR (7 DOWNTO 0);
		PORT_KEYS:     in std_logic_vector (2 downto 0);
		reset:   IN std_logic;
		
		----------OUTPUTS----------
		HEX01_OUT,HEX23_OUT,HEX45_OUT: OUT STD_LOGIC_VECTOR(13 downto 0);
		LEDR: OUT STD_LOGIC_VECTOR( 7 DOWNTO 0);
		PWMout: out std_logic;
		
		
		-------debug OutPuts------------
		
		--PC						 : OUT  STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		Instruction_out	   		 : OUT 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );	
		adress_from_cpu_o   	 : OUT 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		DATA_from_cpu_o	    	 : OUT 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		
		DATA_from_peripherials_o : OUT 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
			
		IFG_oo       : out std_logic_vector(7 downto 0);
		--TYPE_oo      : out std_logic_vector(4 downto 0);
		irq_clear_o  : out std_logic_vector(7 downto 0);
		eint_o       : out std_logic_vector(7 downto 0);
		
		jal_address_out : out std_logic_vector(31 downto 0);
		q: out std_logic_vector(31 downto 0);
		--r: out std_logic_vector(31 downto 0);
			
		
		Memwrite_out_o,Memread_out_o 	: OUT 	STD_LOGIC ;
		GIE_o,INTR_o,INTA_o 			: out std_logic;
		
		data_from_buss_enable_o : out std_logic


);
end component;

COMPONENT TOPS_tester IS
   PORT( 
		Clkin:   OUT STD_LOGIC;
		PORT_SW: OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		reset:   OUT std_logic;
		PORT_KEYS : out std_logic_vector(2 downto 0)
   );

-- Declarations

END COMPONENT ;

	

   -- Optional embedded configurations
   -- pragma synthesis_off
   --FOR ALL : TOPS USE ENTITY work.tops;
  -- FOR ALL : TOPS_tester USE ENTITY work.tops_tester;
   -- pragma synthesis_on
   
		----------INPUTS----------
		signal Clkin:    STD_LOGIC;
		signal PORT_SW:  STD_LOGIC_VECTOR (7 DOWNTO 0);
		signal PORT_KEYS:      std_logic_vector (2 downto 0);
		signal reset:    std_logic;
		
		----------OUTPUTS----------
		signal HEX01_OUT,HEX23_OUT,HEX45_OUT:  STD_LOGIC_VECTOR(13 downto 0);
		signal LEDR:  STD_LOGIC_VECTOR( 7 DOWNTO 0);
		signal PWMout:  std_logic;
		
		
		-------debug OutPuts------------
		
		--PC						 :   STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		signal Instruction_out	   		 :  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );	
		signal adress_from_cpu_o   	 :  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		signal DATA_from_cpu_o	    	 :  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		--DATA_from_gpio_top_o	 :  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		signal DATA_from_peripherials_o :  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
			
		signal IFG_oo       :  std_logic_vector(7 downto 0);
		--TYPE_oo      :  std_logic_vector(4 downto 0);
		signal irq_clear_o  :  std_logic_vector(7 downto 0);
		signal eint_o       :  std_logic_vector(7 downto 0);
		
		signal jal_address_out :  std_logic_vector(31 downto 0);
		signal q:  std_logic_vector(31 downto 0);
		--r: out std_logic_vector(31 downto 0);
			
		
		signal Memwrite_out_o,Memread_out_o 	:  	STD_LOGIC ;
		signal GIE_o,INTR_o,INTA_o 			:  std_logic;
		
		signal data_from_buss_enable_o :  std_logic;


BEGIN

   -- Instance port mappings.
   U_0 : top
	  generic map (k=>k)
      PORT MAP (
         Clkin            => Clkin,
         PORT_SW          => PORT_SW,
		 PORT_KEYS			 =>PORT_KEYS,
         reset            => reset,
         HEX01_OUT 		  => HEX01_OUT,
         HEX23_OUT 		  => HEX23_OUT,
         HEX45_OUT 		  => HEX45_OUT,
         LEDR             => LEDR,
		 PWMout 		  => PWMout,
		 

		adress_from_cpu_o=>adress_from_cpu_o,

		DATA_from_cpu_o=>DATA_from_cpu_o,

		Instruction_out=>Instruction_out,
		Memread_out_o=>Memread_out_o,
		Memwrite_out_o=>Memwrite_out_o,
		DATA_from_peripherials_o =>DATA_from_peripherials_o,
			
		IFG_oo   =>IFG_oo,

		irq_clear_o => irq_clear_o,
		eint_o       => eint_o,
		
		jal_address_out => jal_address_out,
		q =>q ,
			
		
		GIE_o => GIE_o,
		INTR_o => INTR_o,
		INTA_o => INTA_o,
		
		data_from_buss_enable_o => data_from_buss_enable_o
	
      );
   U_1 : TOPS_tester
      PORT MAP (
         Clkin            => Clkin,
         PORT_SW          => PORT_SW,
         reset            => reset,
		 PORT_KEYS		=> PORT_KEYS	
      );

END struct;
